# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 886dcb81f60587c9727da79795a9b3b22b039ab407cecf0ed2020086222fcce1953b0d7e0251cec751274a9f8e7ef96e6dc3fa4a0752eaba9deb23232c6302cd

test:
  secret_key_base: ccacb80a0030a1560d36fe82756fcabfc83c87e3c16381dc2529acb6d8781bbccc4af9183fe841e0b2157bd34b256abf203c6499bd506124f5e3d08916889423

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
